In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('NNI_Index.csv')
df

,Country Name,Country Code,Indicator Name,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,AFG,Adjusted net national income (current US$),8.818972e+09,9.040695e+09,1.107780e+10,1.402680e+10,1.590421e+10,1.812556e+10,1.774544e+10,1.796899e+10,1.667600e+10,1.697400e+10
1,Angola,AGO,Adjusted net national income (current US$),1.321322e+10,5.477561e+09,2.035343e+10,2.559484e+10,2.949041e+10,3.730638e+10,4.822550e+10,5.628679e+10,5.747356e+10,5.121444e+10
2,Albania,ALB,Adjusted net national income (current US$),9.930524e+09,1.167525e+10,1.060608e+10,1.028312e+10,1.118723e+10,1.056092e+10,1.119388e+10,1.137504e+10,9.963562e+09,1.037382e+10
3,United Arab Emirates,ARE,Adjusted net national income (current US$),2.270000e+11,2.680000e+11,2.190000e+11,2.630000e+11,3.130000e+11,3.340000e+11,3.530000e+11,3.650000e+11,3.310000e+11,3.210000e+11
4,Argentina,ARG,Adjusted net national income (current US$),2.430000e+11,3.050000e+11,2.820000e+11,3.610000e+11,4.550000e+11,4.710000e+11,4.770000e+11,4.530000e+11,5.090000e+11,4.700000e+11
5,Armenia,ARM,Adjusted net national income (current US$),8.466157e+09,1.088149e+10,7.867009e+09,8.396312e+09,9.039521e+09,9.453687e+09,1.016848e+10,1.043255e+10,9.257712e+09,9.031276e+09
6,Australia,AUS,Adjusted net national income (current US$),6.450000e+11,7.960000e+11,7.170000e+11,8.790000e+11,1.060000e+12,1.190000e+12,1.220000e+12,1.120000e+12,1.050000e+12,9.410000e+11
7,Austria,AUT,Adjusted net national income (current US$),3.250000e+11,3.620000e+11,3.300000e+11,3.260000e+11,3.570000e+11,3.370000e+11,3.540000e+11,3.620000e+11,3.110000e+11,3.200000e+11
8,Azerbaijan,AZE,Adjusted net national income (current US$),1.758270e+10,2.898243e+10,3.046540e+10,3.550011e+10,4.255426e+10,4.788493e+10,5.438009e+10,5.822740e+10,4.321721e+10,2.805138e+10
9,Burundi,BDI,Adjusted net national income (current US$),7.216629e+08,8.561240e+08,9.684768e+08,1.287176e+09,1.501448e+09,1.771919e+09,1.973064e+09,2.296405e+09,2.218417e+09,2.122721e+09
10,Belgium,BEL,Adjusted net national income (current US$),3.930000e+11,4.340000e+11,3.910000e+11,4.060000e+11,4.300000e+11,4.120000e+11,4.270000e+11,4.310000e+11,3.660000e+11,3.770000e+11
11,Benin,BEN,Adjusted net national income (current US$),5.058095e+09,6.066146e+09,5.982247e+09,5.862986e+09,6.595986e+09,6.832147e+09,7.661880e+09,8.123732e+09,6.930721e+09,7.141447e+09
12,Burkina Faso,BFA,Adjusted net national income (current US$),5.866049e+09,7.115530e+09,6.975652e+09,7.094641e+09,8.056189e+09,8.573640e+09,9.245467e+09,9.400146e+09,7.515370e+09,8.486793e+09
13,Bangladesh,BGD,Adjusted net national income (current US$),7.678247e+10,8.953266e+10,1.010000e+11,1.130000e+11,1.260000e+11,1.310000e+11,1.480000e+11,1.680000e+11,1.890000e+11,2.130000e+11
14,Bulgaria,BGR,Adjusted net national income (current US$),3.496650e+10,4.476156e+10,4.319745e+10,4.127003e+10,4.665089e+10,4.505529e+10,4.643139e+10,4.741515e+10,4.161325e+10,4.509114e+10
15,Bahrain,BHR,Adjusted net national income (current US$),1.904758e+10,2.195706e+10,1.824768e+10,2.081236e+10,2.202633e+10,2.314499e+10,2.446044e+10,2.362434e+10,2.624878e+10,2.694529e+10
16,"Bahamas, The",BHS,Adjusted net national income (current US$),7.534741e+09,7.579961e+09,7.111219e+09,7.109346e+09,7.106037e+09,9.766176e+09,9.622523e+09,9.621246e+09,9.833900e+09,9.625654e+09
17,Bosnia and Herzegovina,BIH,Adjusted net national income (current US$),1.443005e+10,1.756009e+10,1.617199e+10,1.528328e+10,1.624054e+10,1.484185e+10,1.592234e+10,1.611912e+10,1.403278e+10,1.452519e+10
18,Belarus,BLR,Adjusted net national income (current US$),4.021093e+10,5.415893e+10,4.336690e+10,5.091652e+10,5.496507e+10,5.839075e+10,6.631451e+10,6.950077e+10,4.906703e+10,4.082816e+10
19,Belize,BLZ,Adjusted net national income (current US$),8.983018e+08,9.205178e+08,9.830093e+08,9.597330e+08,1.060008e+09,1.140244e+09,1.182402e+09,1.271891e+09,1.365241e+09,1.349066e+09
20,Bolivia,BOL,Adjusted net national income (current US$),1.003947e+10,1.324051e+10,1.417875e+10,1.575693e+10,1.847896e+10,2.032943e+10,2.299343e+10,2.487741e+10,2.664548e+10,2.752910e+10
21,Brazil,BRA,Adjusted net national income (current US$),1.140000e+12,1.370000e+12,1.380000e+12,1.840000e+12,2.180000e+12,2.070000e+12,2.110000e+12,2.070000e+12,1.540000e+12,1.530000e+12
22,Barbados,BRB,Adjusted net national income (current US$),3.822800e+09,3.867312e+09,3.766854e+09,3.856984e+09,3.815685e+09,3.926283e+09,3.906495e+09,3.902285e+09,3.870514e+09,3.818070e+09
23,Brunei Darussalam,BRN,Adjusted net national income (current US$),9.262167e+09,1.069895e+10,8.518548e+09,1.048855e+10,1.273360e+10,1.352148e+10,1.376265e+10,1.356546e+10,1.163278e+10,1.049916e+10
24,Bhutan,BTN,Adjusted net national income (current US$),1.056309e+09,1.094381e+09,1.087203e+09,1.323624e+09,1.514474e+09,1.499592e+09,1.501649e+09,1.623009e+09,1.662887e+09,1.754481e+09
25,Botswana,BWA,Adjusted net national income (current US$),7.613670e+09,7.643978e+09,7.108136e+09,9.237607e+09,1.230428e+10,1.144517e+10,1.120898e+10,1.232565e+10,1.116717e+10,1.196974e+10
26,Canada,CAN,Adjusted net national income (current US$),1.190000e+12,1.240000e+12,1.100000e+12,1.310000e+12,1.450000e+12,1.480000e+12,1.500000e+12,1.460000e+12,1.260000e+12,1.240000e+12
27,Switzerland,CHE,Adjusted net national income (current US$),3.850000e+11,4.030000e+11,4.350000e+11,4.970000e+11,5.630000e+11,5.450000e+11,5.600000e+11,5.650000e+11,5.530000e+11,5.310000e+11
28,Chile,CHL,Adjusted net national income (current US$),1.130000e+11,1.240000e+11,1.250000e+11,1.560000e+11,1.820000e+11,1.990000e+11,2.110000e+11,2.000000e+11,1.910000e+11,1.950000e+11
29,China,CHN,Adjusted net national income (current US$),2.970000e+12,3.720000e+12,4.250000e+12,4.910000e+12,5.890000e+12,6.760000e+12,7.490000e+12,8.270000e+12,8.710000e+12,8.700000e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Slovak Republic,SVK,Adjusted net national income (current US$),6.814044e+10,8.032899e+10,7.046518e+10,6.977099e+10,7.498826e+10,7.277944e+10,7.720389e+10,7.856026e+10,6.803451e+10,6.989392e+10
137,Slovenia,SVN,Adjusted net national income (current US$),3.871032e+10,4.450453e+10,3.974905e+10,3.780081e+10,4.029047e+10,3.577615e+10,3.720912e+10,3.909306e+10,3.290719e+10,3.436254e+10
138,Sweden,SWE,Adjusted net national income (current US$),4.280000e+11,4.490000e+11,3.650000e+11,4.190000e+11,4.810000e+11,4.640000e+11,4.940000e+11,4.900000e+11,4.240000e+11,4.390000e+11
139,Eswatini,SWZ,Adjusted net national income (current US$),3.046423e+09,2.837100e+09,3.020072e+09,3.623016e+09,4.155452e+09,4.158529e+09,4.004140e+09,3.802666e+09,3.507464e+09,3.199141e+09
140,Seychelles,SYC,Adjusted net national income (current US$),9.096048e+08,7.878950e+08,7.447013e+08,8.212790e+08,9.003822e+08,9.670031e+08,1.179306e+09,1.153513e+09,1.153312e+09,1.203940e+09
141,Chad,TCD,Adjusted net national income (current US$),5.014102e+09,5.763700e+09,7.077678e+09,8.030509e+09,8.631351e+09,9.058550e+09,9.707132e+09,1.055216e+10,8.867234e+09,7.741892e+09
142,Togo,TGO,Adjusted net national income (current US$),2.196441e+09,2.191753e+09,2.205692e+09,2.154556e+09,2.219426e+09,2.054765e+09,2.295198e+09,2.974401e+09,2.766320e+09,3.020251e+09
143,Thailand,THA,Adjusted net national income (current US$),2.110000e+11,2.300000e+11,2.230000e+11,2.700000e+11,2.960000e+11,3.060000e+11,3.170000e+11,3.090000e+11,3.080000e+11,3.090000e+11
144,Tajikistan,TJK,Adjusted net national income (current US$),3.306288e+09,4.598225e+09,4.506101e+09,5.871960e+09,6.898047e+09,8.258327e+09,9.209802e+09,9.968074e+09,8.309157e+09,7.147141e+09
145,Tonga,TON,Adjusted net national income (current US$),2.828738e+08,3.280123e+08,3.008900e+08,3.474913e+08,3.962595e+08,4.432106e+08,4.229371e+08,4.086973e+08,4.013167e+08,3.680360e+08
146,Trinidad and Tobago,TTO,Adjusted net national income (current US$),1.492498e+10,1.981588e+10,1.404602e+10,1.665165e+10,1.638338e+10,1.600837e+10,1.800455e+10,1.783744e+10,1.893099e+10,1.770207e+10
147,Tunisia,TUN,Adjusted net national income (current US$),2.932520e+10,3.198519e+10,3.336752e+10,3.347587e+10,3.435209e+10,3.388368e+10,3.459012e+10,3.635532e+10,3.336634e+10,3.179497e+10
148,Turkey,TUR,Adjusted net national income (current US$),5.650000e+11,6.390000e+11,5.310000e+11,6.480000e+11,7.040000e+11,7.380000e+11,8.060000e+11,7.880000e+11,7.230000e+11,7.210000e+11
149,Tanzania,TZA,Adjusted net national income (current US$),1.897054e+10,2.406610e+10,2.510437e+10,2.759450e+10,2.979630e+10,3.442253e+10,3.986501e+10,4.362862e+10,4.061244e+10,4.211990e+10
150,Uganda,UGA,Adjusted net national income (current US$),9.292209e+09,1.050521e+10,1.396672e+10,1.582309e+10,1.531386e+10,1.701723e+10,1.800865e+10,2.010878e+10,1.940126e+10,1.635829e+10
151,Ukraine,UKR,Adjusted net national income (current US$),1.190000e+11,1.520000e+11,9.466587e+10,1.120000e+11,1.330000e+11,1.470000e+11,1.530000e+11,1.130000e+11,7.775508e+10,7.989010e+10
152,Uruguay,URY,Adjusted net national income (current US$),2.044796e+10,2.611617e+10,2.720248e+10,3.406732e+10,4.100554e+10,4.404373e+10,4.933747e+10,4.880796e+10,4.564846e+10,4.516344e+10
153,United States,USA,Adjusted net national income (current US$),1.220000e+13,1.230000e+13,1.210000e+13,1.270000e+13,1.330000e+13,1.400000e+13,1.440000e+13,1.510000e+13,1.570000e+13,1.600000e+13
154,Uzbekistan,UZB,Adjusted net national income (current US$),1.746645e+10,2.331991e+10,2.755122e+10,3.457551e+10,3.856768e+10,4.263616e+10,5.010164e+10,5.532058e+10,5.983714e+10,6.006231e+10
155,St. Vincent and the Grenadines,VCT,Adjusted net national income (current US$),5.786765e+08,6.170166e+08,6.004111e+08,5.895434e+08,5.725430e+08,5.655691e+08,5.887229e+08,5.877961e+08,5.933652e+08,5.873283e+08
156,Vietnam,VNM,Adjusted net national income (current US$),6.258744e+10,7.928742e+10,8.547963e+10,9.390566e+10,1.080000e+11,1.260000e+11,1.390000e+11,1.520000e+11,1.590000e+11,1.710000e+11
157,Samoa,WSM,Adjusted net national income (current US$),4.510764e+08,5.261162e+08,4.696518e+08,5.491915e+08,6.309798e+08,6.779609e+08,6.858183e+08,6.886851e+08,6.994795e+08,6.820720e+08
158,"Yemen, Rep.",YEM,Adjusted net national income (current US$),1.422528e+10,1.777237e+10,1.951207e+10,2.332575e+10,2.527118e+10,2.941260e+10,3.339845e+10,3.636556e+10,3.454431e+10,2.575884e+10
159,South Africa,ZAF,Adjusted net national income (current US$),2.400000e+11,2.200000e+11,2.400000e+11,3.020000e+11,3.340000e+11,3.200000e+11,2.950000e+11,2.820000e+11,2.590000e+11,2.390000e+11
160,Zambia,ZMB,Adjusted net national income (current US$),9.118969e+09,1.250481e+10,1.130037e+10,1.358906e+10,1.615001e+10,1.889853e+10,2.040330e+10,2.061153e+10,1.608440e+10,1.603736e+10
161,Zimbabwe,ZWE,Adjusted net national income (current US$),4.472660e+09,3.599817e+09,6.971372e+09,8.000625e+09,8.824356e+09,9.727580e+09,1.148320e+10,1.196292e+10,1.192436e+10,1.212059e+10
162,\t\t\t\t\t\t\t\t\t\t\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,\t\t\t\t\t\t\t\t\t\t\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,\t\t\t\t\t\t\t\t\t\t\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,\t\t\t\t\t\t\t\t\t\t\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
"France" in df["Country Name"].values

True

In [5]:
country = input("Choose a country (Format: Argentina): " )
while country not in df["Country Name"].values:
    print("Country not found")
    country = input("Choose a country (Format: Argentina): " )

Choose a country (Format: Argentina):
Country not found
Choose a country (Format: Argentina):
Country not found
Choose a country (Format: Argentina):
Country not found
Choose a country (Format: Argentina): France

In [6]:
country_row = df[df["Country Name"] == country].iloc[:,3:13]
yoy_nni_country = country_row.values[0]

In [11]:
country_row.columns.values

array(['2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016'], dtype=object)

In [49]:
year_nni_country = country_row.T.index == yoy_nni_country.min()
min_year_country = country_row.T.index[yoy_nni_country == yoy_nni_country.min()].values[0]
max_year_country = country_row.T.index[yoy_nni_country == yoy_nni_country.max()].values[0]

In [50]:
print("\n{} is the year with the min NNI at: {:.3E}".format(min_year_country,yoy_nni_country.min()))

2015 is the year with the min NNI at: 2.035E+12

In [52]:
print("\n{} is the year with the max NNi at: {:.3E}".format(max_year_country,yoy_nni_country.max()))

2008 is the year with the max NNi at: 2.484E+12

In [242]:
"{:.3E}".format(yoy_nni_country.mean())

'2.272E+12'

In [243]:
"{:.3E}".format(np.median(yoy_nni_country))

'2.269E+12'

In [250]:
CAGR = "{:.3f}%".format((yoy_nni_country[-1] / yoy_nni_country[0]) ** (1/10) - 1)
CAGR

'-0.010%'

In [251]:
year = input("Choose a year (Format: XXXX): " )

Choose a year (Format: XXXX): 2012

In [272]:
max_year = df[["Country Name", year]][df[year] == df[year].max()]
max_country = max_year["Country Name"].values[0]

"{}, {:.3E}".format(max_country, max_year[year].values[0])

'United States, 1.400E+13'

In [274]:
min_year = df[["Country Name", year]][df[year] == df[year].min()]
min_country = min_year["Country Name"].values[0]

"{}, {:.3E}".format(min_country, min_year[year].values[0])

'Sao Tome and Principe, 1.438E+08'

In [275]:
"This is the mean: {:.3E}".format(df[year].mean())

'This is the mean: 3.825E+11'

In [276]:
"This is the median: {:.3E}".format(df[year].median())

'This is the median: 3.043E+10'